import { Agent, AgentTemplate } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "1",
    name: "Alexandre",
    sector: "Finance",
    tone: "formel",
    instructions: "Assistant pour cabinet de conseil financier. Toujours professionnel et précis.",
    enabled: true,
    lastRun: "Il y a 2 min",
    channels: {
      whatsapp: { enabled: true, number: "+33612345678" },
      email: { enabled: true, address: "contact@example.com" },
      telegram: { enabled: false },
      imessage: { enabled: false, premium: true },
    },
    skills: { emails: true, calendar: true, prospection: true, crm: true, reminders: true },
    activity: [
      { id: "a1", timestamp: "23:30", action: "Email traité", details: "Réponse envoyée à Simon (devis)" },
      { id: "a2", timestamp: "23:15", action: "Rappel", details: "RDV demain 10h avec Client X" },
      { id: "a3", timestamp: "22:00", action: "CRM", details: "Pipeline mis à jour - 3 opportunités" },
    ],
  },
  {
    id: "2",
    name: "Marie",
    sector: "Support Client",
    tone: "friendly",
    instructions: "Répond aux tickets clients avec empathie. Escalade les problèmes complexes.",
    enabled: true,
    lastRun: "Il y a 1h",
    channels: {
      whatsapp: { enabled: false },
      email: { enabled: true, address: "support@example.com" },
      telegram: { enabled: true, token: "bot_xxx" },
      imessage: { enabled: false, premium: true },
    },
    skills: { emails: true, calendar: false, prospection: false, crm: true, reminders: true },
    activity: [
      { id: "b1", timestamp: "22:45", action: "Ticket résolu", details: "Client #412 - problème de connexion" },
      { id: "b2", timestamp: "22:30", action: "Email envoyé", details: "Suivi satisfaction client #398" },
    ],
  },
  {
    id: "3",
    name: "Hugo",
    sector: "Marketing",
    tone: "direct",
    instructions: "Community manager. Propose des posts, veille concurrentielle, analyse des stats.",
    enabled: false,
    lastRun: null,
    channels: {
      whatsapp: { enabled: false },
      email: { enabled: false },
      telegram: { enabled: false },
      imessage: { enabled: false, premium: true },
    },
    skills: { emails: false, calendar: false, prospection: true, crm: false, reminders: false },
    activity: [],
  },
];

export const agentTemplates: AgentTemplate[] = [
  {
    id: "t1",
    name: "Assistant Commercial",
    description: "Prospection, relances, suivi CRM, qualification de leads",
    icon: "💼",
    sector: "Commercial",
    tone: "direct",
    defaultSkills: { emails: true, calendar: true, prospection: true, crm: true, reminders: true },
    defaultChannels: { whatsapp: { enabled: true }, email: { enabled: true } },
  },
  {
    id: "t2",
    name: "Gestionnaire Emails",
    description: "Tri intelligent, réponses automatiques, suivi des conversations",
    icon: "📧",
    sector: "Administration",
    tone: "formel",
    defaultSkills: { emails: true, calendar: false, prospection: false, crm: false, reminders: true },
    defaultChannels: { email: { enabled: true } },
  },
  {
    id: "t3",
    name: "Assistant RDV",
    description: "Préparation, notes de réunion, suivi des actions",
    icon: "📅",
    sector: "Organisation",
    tone: "friendly",
    defaultSkills: { emails: false, calendar: true, prospection: false, crm: false, reminders: true },
    defaultChannels: { email: { enabled: true } },
  },
  {
    id: "t4",
    name: "Community Manager",
    description: "Création de contenu, veille, statistiques, programmation",
    icon: "📱",
    sector: "Marketing",
    tone: "friendly",
    defaultSkills: { emails: false, calendar: true, prospection: false, crm: false, reminders: true },
    defaultChannels: { telegram: { enabled: true } },
  },
  {
    id: "t5",
    name: "Support Client",
    description: "Tickets, FAQ, satisfaction client, escalade",
    icon: "🎧",
    sector: "Support",
    tone: "friendly",
    defaultSkills: { emails: true, calendar: false, prospection: false, crm: true, reminders: true },
    defaultChannels: { email: { enabled: true }, whatsapp: { enabled: true } },
  },
  {
    id: "t6",
    name: "Assistant Comptable",
    description: "Factures, relances impayés, suivi Pennylane",
    icon: "🧾",
    sector: "Comptabilité",
    tone: "formel",
    defaultSkills: { emails: true, calendar: false, prospection: false, crm: false, reminders: true },
    defaultChannels: { email: { enabled: true } },
  },
];
